### ISSUE TITLE
kSu 'Help Tips' tab unreadable with dark desktop theme

### ISSUE THREAD

**Issue by mmuman** [easyw/kicadStepUpMod#163]
The HTML probably enforced the text color but not the background, so when using a dark theme it ends up with black text over black background, one has to select the text to be able to read it.

![Screenshot_20230205_002634](https://user-images.githubusercontent.com/470143/216793763-7bc62fa7-8e5c-4960-96d3-fdd2319c1b9b.png)

**Comment by easyw** [comment]
@mmuman 
which is your theme andos you are using?

**Comment by mmuman** [comment]
From `neofetch`:
```
OS: Debian GNU/Linux bookworm/sid x86_64 
Kernel: 6.1.0-3-amd64 
DE: Plasma 5.26.90 
WM: KWin 
WM Theme: Neon_Knights_Blue 
Theme: Materia Manjaro Dark [Plasma], Breeze [GTK3] 
Icons: Simply-Blue-Circles [Plasma], Simply-Blue-Circles [GTK2/3] 
```

**Comment by easyw** [comment]
@mmuman 
it should be fixed with this commit https://github.com/easyw/kicadStepUpMod/commit/c9ca514c6bfb44ca027ee9019c2a362654604e34

would you mind to post the Help results in your OS after this update?

**Comment by mmuman** [comment]
Hmm still happens with 10.7.9.
![Screenshot_20230209_162657](https://user-images.githubusercontent.com/470143/217856854-24aa577f-7f4e-4ffb-9bfc-31e32779fe50.png)

**Comment by easyw** [comment]
@mmuman 
could you retry now
https://github.com/easyw/kicadStepUpMod/commit/6cc836fbdfa91b4b36d397e4a8a99c489c8d42f6

**Comment by mmuman** [comment]
Almost there, just missing the second line I think.
![Screenshot_20230209_171330](https://user-images.githubusercontent.com/470143/217870692-3a765cda-dd40-4816-953b-3f35e784134a.png)

**Comment by easyw** [comment]
@mmuman 
please try it again https://github.com/easyw/kicadStepUpMod/commit/d535e9e4b532f1a8c8f84b7d43e78eb83c6391ae
would you please test the help button in kSU 

![help-button](https://user-images.githubusercontent.com/3032347/217886802-9ffea625-53ac-4787-bc61-1a41ffa2e28b.png)

**Comment by mmuman** [comment]
Everything seems fine, thanks! :+1: 
![Screenshot_20230209_190322](https://user-images.githubusercontent.com/470143/217899428-14675db5-93b5-462e-a940-0b5e17b91163.png)
